### model
model_name_or_path: /volume/pt-train/models/Qwen3-8B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /volume/pt-train/users/wzhang/wjj-workspace/LightSFT-Qwen3-Humaneval/src/training/LLaMA-Factory/examples/deepspeed/ds_z3_config.json  # optional, enable if available

### dataset
dataset: alpaca_en_demo
dataset_dir: data

template: qwen
cutoff_len: 2048
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3-8b/full/sft
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb
run_name: qwen3-8b-full-sft

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval (optional)
# eval_dataset: custom_alpaca
# val_size: 0.02
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 1000
